import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:dmtools_mermaid_renderer/src/mermaid_render_options.dart';
import 'package:dmtools_mermaid_renderer/src/svg_normalizer.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_js/flutter_js.dart';
import 'package:flutter_svg/flutter_svg.dart';

const bool _kDebugLogs = false;

// ignore: avoid_print
void _log(String msg) {
  if (_kDebugLogs) {
    // ignore: avoid_print
    print('[MermaidRenderer] $msg');
  }
}

/// Dart / Flutter counterpart to the Java {@code MermaidRenderer} class.
///
/// Renders Mermaid diagram DSL to SVG or PNG without a browser:
///
///  * JavaScript engine: flutter_js (QuickJS on Android/Linux, JavaScriptCore
///    on iOS/macOS) — same role as GraalJS in the Java version.
///  * Text metrics: falls back to the built-in JS heuristics inside the bundle
///    (same estimates used when javaMetrics=null in the Java shim).
///  * SVG→PNG: flutter_svg + dart:ui PictureRecorder — replaces Apache Batik.
///
/// Typical usage:
///
/// ```dart
/// final renderer = MermaidRenderer();
/// await renderer.init();
///
/// final svg = await renderer.renderToSvg('flowchart TD; A --> B');
/// final png = await renderer.renderToPng('flowchart TD; A --> B');
///
/// renderer.dispose();
/// ```
class MermaidRenderer {
  late final JavascriptRuntime _js;
  bool _initialized = false;

  // Serialise all renders so only one JS polling loop runs at a time.
  // Multiple concurrent loops each call _js.evaluate() every 50 ms which
  // blocks the Dart event loop and causes UI jank.
  Future<void> _renderQueue = Future.value();

  /// Asset path of the mermaid-renderer.js bundle (overridable for testing).
  final String jsAssetPath;

  MermaidRenderer({
    this.jsAssetPath =
        'packages/dmtools_mermaid_renderer/assets/mermaid/mermaid-renderer.js',
  });

  // ─── lifecycle ────────────────────────────────────────────────────────────

  /// Load and evaluate the Mermaid JS bundle.
  ///
  /// Must be called once before [renderToSvg] / [renderToPng].
  /// Safe to call from [WidgetsFlutterBinding.ensureInitialized()] context.
  ///
  /// ⚠️  On desktop platforms (macOS/Windows/Linux) the JS bundle is ~11 MB
  /// and is evaluated synchronously via FFI.  Expect this to block the Dart
  /// event loop for up to a few seconds on the first call.  Call this early
  /// (e.g. at app start) if you want it to complete before the user opens a
  /// markdown panel.
  Future<void> init() async {
    if (_initialized) return;
    _log('init() start');
    _js = getJavascriptRuntime();
    _log('JS runtime created: ${_js.runtimeType}');
    // Yield one frame so the UI is responsive before the heavy sync eval.
    await Future<void>.delayed(Duration.zero);
    final jsSource = await rootBundle.loadString(jsAssetPath);
    _log('JS bundle loaded (${jsSource.length} chars), evaluating...');
    // Yield again after loading so Flutter can process any pending events.
    await Future<void>.delayed(Duration.zero);
    _js.evaluate(jsSource);
    _initialized = true;
    _log('init() complete');
  }

  /// Free the JS runtime resources.
  void dispose() {
    if (_initialized) {
      _js.dispose();
      _initialized = false;
    }
  }

  // ─── public API ───────────────────────────────────────────────────────────

  /// Render [definition] to a normalised SVG string.
  ///
  /// The output is suitable for display with [SvgPicture.string] and opens
  /// correctly in Affinity Designer / Inkscape.
  Future<String> renderToSvg(
    String definition, {
    MermaidRenderOptions? options,
  }) async {
    _assertInitialized();
    // Serialise: chain onto the existing queue using whenComplete so that
    // errors in one render don't poison the queue for subsequent renders.
    final completer = Completer<String>();
    _renderQueue = _renderQueue.whenComplete(() async {
      try {
        final rawSvg = await _jsRender(definition, options?.config);
        completer.complete(SvgNormalizer.normalize(rawSvg));
      } catch (e, st) {
        completer.completeError(e, st);
      }
    });
    return completer.future;
  }

  /// Render [definition] to PNG bytes.
  ///
  /// The PNG is generated by rendering the normalised SVG through
  /// flutter_svg + dart:ui PictureRecorder (white background, device-pixel
  /// resolution = 1).
  ///
  /// Requires the Flutter widget binding to be initialised:
  /// ```dart
  /// WidgetsFlutterBinding.ensureInitialized();
  /// ```
  Future<Uint8List> renderToPng(
    String definition, {
    MermaidRenderOptions? options,
  }) async {
    final svg = await renderToSvg(definition, options: options);
    return svgToPng(svg, backgroundColor: options?.backgroundColor);
  }

  // ─── helpers ──────────────────────────────────────────────────────────────

  void _assertInitialized() {
    if (!_initialized) {
      throw StateError(
          'MermaidRenderer not initialised. Call init() before rendering.');
    }
  }

  int _renderCallId = 0;

  Future<String> _jsRender(
    String definition,
    Map<String, Object?>? config,
  ) async {
    // renderMermaidToSvg is an async JS function that internally uses setTimeout
    // and requestAnimationFrame (polyfilled via __dmtoolsTimerQueue).
    // flutter_js has no automatic event loop, so we:
    //   1. Store the resolve/reject value in named globals.
    //   2. Poll every 50 ms, draining __dmtoolsTimerQueue each time, until done.
    //   3. Timeout after 30 s.
    final id = _renderCallId++;
    final svgVar = '__dmtools_r${id}_svg';
    final errVar = '__dmtools_r${id}_err';
    final doneVar = '__dmtools_r${id}_done';

    _log('_jsRender[$id] start, definition length=${definition.length}');
    _js.evaluate('''
      globalThis.$svgVar = undefined;
      globalThis.$errVar = undefined;
      globalThis.$doneVar = false;
      renderMermaidToSvg(${jsonEncode(definition)}, null, ${jsonEncode(config)})
        .then(function(svg) {
          globalThis.$svgVar = svg;
          globalThis.$doneVar = true;
        })
        .catch(function(e) {
          globalThis.$errVar = String(e);
          globalThis.$doneVar = true;
        });
    ''');
    _log('_jsRender[$id] JS kicked off, starting poll...');

    const maxAttempts = 300; // 30 s at 100 ms intervals
    for (var i = 0; i < maxAttempts; i++) {
      await Future<void>.delayed(const Duration(milliseconds: 100));
      // Drain the JS timer / rAF queue so mermaid's async internals can progress.
      _js.evaluate('__dmtoolsDrainTimers();');

      final isDone = _js.evaluate('!!globalThis.$doneVar;').stringResult;
      if (i % 10 == 0) _log('_jsRender[$id] poll attempt $i, isDone=$isDone');
      if (isDone == 'true') {
        final hasErr = _js
            .evaluate(
              'globalThis.$errVar !== undefined;',
            )
            .stringResult;
        if (hasErr == 'true') {
          final err = _js.evaluate('String(globalThis.$errVar);').stringResult;
          _log('_jsRender[$id] FAILED: $err');
          _cleanup(svgVar, errVar, doneVar);
          throw Exception('Mermaid rendering failed: $err');
        }
        final svg = _js.evaluate('String(globalThis.$svgVar);').stringResult;
        _log('_jsRender[$id] SUCCESS, svg length=${svg.length}');
        _cleanup(svgVar, errVar, doneVar);
        return svg;
      }
    }

    _log('_jsRender[$id] TIMEOUT after 30s');
    _cleanup(svgVar, errVar, doneVar);
    throw Exception('Mermaid rendering timed out after 30 s');
  }

  void _cleanup(String svgVar, String errVar, String doneVar) {
    _js.evaluate(
      'delete globalThis.$svgVar;'
      'delete globalThis.$errVar;'
      'delete globalThis.$doneVar;',
    );
  }

  // ─── SVG → PNG conversion (static, reusable) ──────────────────────────────

  /// Convert a normalised SVG string to PNG bytes using flutter_svg + dart:ui.
  ///
  /// The SVG natural [viewBox] / [width] / [height] is used for the output
  /// dimensions.  Supply explicit [width] / [height] to override.
  ///
  /// On systems where `rsvg-convert` (librsvg) is on PATH it is used for
  /// full-fidelity rendering including fonts and text.  Otherwise falls back
  /// to `flutter_svg` + `dart:ui` which renders shapes and paths correctly but
  /// may not render text labels.
  static Future<Uint8List> svgToPng(
    String svgString, {
    double? width,
    double? height,
    String? backgroundColor,
  }) async {
    _log(
        'svgToPng() start, svg length=${svgString.length}, width=$width, height=$height');

    // Try rsvg-convert first — it handles all SVG text/font features that
    // vector_graphics_compiler currently does not support.
    _log('svgToPng() trying rsvg-convert...');
    final rsvgPng = await _svgToPngViaRsvg(
      svgString,
      width,
      height,
      backgroundColor,
    );
    if (rsvgPng != null) {
      _log('svgToPng() SUCCESS via rsvg-convert, png bytes=${rsvgPng.length}');
      return rsvgPng;
    }

    // Fallback: flutter_svg + dart:ui (shapes only, text may be missing).
    _log('svgToPng() falling back to flutter_svg + dart:ui...');
    final png = await _svgToPngViaFlutterSvg(
      svgString,
      width,
      height,
      backgroundColor,
    );
    _log('svgToPng() SUCCESS via flutter_svg, png bytes=${png.length}');
    return png;
  }

  /// Attempt PNG conversion via the `rsvg-convert` CLI (librsvg).
  /// Returns null if rsvg-convert is not found or fails.
  static Future<Uint8List?> _svgToPngViaRsvg(
    String svgString,
    double? width,
    double? height,
    String? backgroundColor,
  ) async {
    try {
      _log('_svgToPngViaRsvg() start');
      // Write SVG to a temp file.
      final tmpSvg = _tmpFile('svg');
      final tmpPng = _tmpFile('png');
      try {
        File(tmpSvg).writeAsStringSync(svgString, encoding: _utf8);

        final args = <String>[
          tmpSvg,
          '-b',
          backgroundColor ?? '#FFFFFF',
          '-o',
          tmpPng,
        ];
        if (width != null) args.addAll(['-w', width.toInt().toString()]);
        if (height != null) args.addAll(['-h', height.toInt().toString()]);

        _log('_svgToPngViaRsvg() running: rsvg-convert ${args.join(" ")}');
        final result = await Process.run('rsvg-convert', args);
        if (result.exitCode != 0) {
          _log(
              '_svgToPngViaRsvg() rsvg-convert failed with exit code ${result.exitCode}: ${result.stderr}');
          return null;
        }

        final png = File(tmpPng);
        if (!png.existsSync()) {
          _log('_svgToPngViaRsvg() output PNG file not found at $tmpPng');
          return null;
        }
        _log('_svgToPngViaRsvg() SUCCESS');
        return png.readAsBytesSync();
      } finally {
        _tryDelete(tmpSvg);
        _tryDelete(tmpPng);
      }
    } on ProcessException catch (e) {
      _log(
          '_svgToPngViaRsvg() ProcessException (rsvg-convert not on PATH): $e');
      return null;
    } catch (e) {
      _log('_svgToPngViaRsvg() Exception: $e');
      return null;
    }
  }

  static Future<Uint8List> _svgToPngViaFlutterSvg(
    String svgString,
    double? width,
    double? height,
    String? backgroundColor,
  ) async {
    _log('_svgToPngViaFlutterSvg() start');
    final (w, h) = _parseDimensions(svgString, width, height);
    _log('_svgToPngViaFlutterSvg() dimensions: w=$w, h=$h');

    // flutter_svg 2.x: SvgStringLoader compiles SVG to the vector_graphics
    // binary format; vg.loadPicture turns that into a ui.Picture.
    _log('_svgToPngViaFlutterSvg() loading SVG via flutter_svg...');
    final loader = SvgStringLoader(svgString);
    final pictureInfo = await vg.loadPicture(loader, null);
    _log(
        '_svgToPngViaFlutterSvg() SVG loaded, picture size: ${pictureInfo.size}');

    final iw = w.toInt();
    final ih = h.toInt();

    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(
      recorder,
      ui.Rect.fromLTWH(0, 0, w, h),
    );

    // White background (matching Java Batik: KEY_BACKGROUND_COLOR = white).
    canvas.drawRect(
      ui.Rect.fromLTWH(0, 0, w, h),
      ui.Paint()..color = _parseColor(backgroundColor),
    );

    // Scale SVG to fit requested dimensions.
    final scaleX = w / pictureInfo.size.width;
    final scaleY = h / pictureInfo.size.height;
    final scale = scaleX < scaleY ? scaleX : scaleY;
    canvas.save();
    canvas.scale(scale);
    canvas.drawPicture(pictureInfo.picture);
    canvas.restore();
    pictureInfo.picture.dispose();

    _log('_svgToPngViaFlutterSvg() picture drawn, encoding to PNG...');
    final picture = recorder.endRecording();
    final image = await picture.toImage(iw, ih);
    picture.dispose();

    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    image.dispose();

    if (byteData == null) {
      throw StateError('dart:ui failed to encode PNG');
    }
    final png = byteData.buffer.asUint8List();
    _log('_svgToPngViaFlutterSvg() SUCCESS, png bytes=${png.length}');
    return png;
  }

  static const Utf8Codec _utf8 = Utf8Codec();

  static ui.Color _parseColor(String? color) {
    if (color == null || color.isEmpty) {
      return const ui.Color(0xFFFFFFFF);
    }
    final normalized = color.startsWith('#') ? color.substring(1) : color;
    final hex =
        normalized.length == 6 ? 'FF$normalized' : normalized.padLeft(8, 'F');
    final value = int.tryParse(hex, radix: 16);
    if (value == null) {
      return const ui.Color(0xFFFFFFFF);
    }
    return ui.Color(value);
  }

  static String _tmpFile(String ext) =>
      '${Directory.systemTemp.path}/dmtools_mermaid_${DateTime.now().microsecondsSinceEpoch}.$ext';

  static void _tryDelete(String path) {
    try {
      File(path).deleteSync();
    } catch (_) {}
  }

  /// Parse width/height from SVG viewBox or width/height attributes.
  static (double, double) _parseDimensions(
      String svg, double? overrideW, double? overrideH) {
    double? w = overrideW;
    double? h = overrideH;

    if (w == null || h == null) {
      // Try viewBox first.
      final vbMatch = RegExp(r'viewBox="([^"]+)"').firstMatch(svg);
      if (vbMatch != null) {
        final parts = vbMatch.group(1)!.trim().split(RegExp(r'[\s,]+'));
        if (parts.length == 4) {
          w ??= double.tryParse(parts[2]);
          h ??= double.tryParse(parts[3]);
        }
      }
      // Fall back to width/height attributes.
      if (w == null) {
        final wm = RegExp(r'\bwidth="([0-9.]+)"').firstMatch(svg);
        if (wm != null) w = double.tryParse(wm.group(1)!);
      }
      if (h == null) {
        final hm = RegExp(r'\bheight="([0-9.]+)"').firstMatch(svg);
        if (hm != null) h = double.tryParse(hm.group(1)!);
      }
    }

    return (w ?? 800.0, h ?? 600.0);
  }
}
