import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/widgets.dart';
import 'package:flutter_js/flutter_js.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'svg_normalizer.dart';

/// Dart / Flutter counterpart to the Java {@code MermaidRenderer} class.
///
/// Renders Mermaid diagram DSL to SVG or PNG without a browser:
///
///  * JavaScript engine: flutter_js (QuickJS on Android/Linux, JavaScriptCore
///    on iOS/macOS) — same role as GraalJS in the Java version.
///  * Text metrics: falls back to the built-in JS heuristics inside the bundle
///    (same estimates used when javaMetrics=null in the Java shim).
///  * SVG→PNG: flutter_svg + dart:ui PictureRecorder — replaces Apache Batik.
///
/// Typical usage:
///
/// ```dart
/// final renderer = MermaidRenderer();
/// await renderer.init();
///
/// final svg = await renderer.renderToSvg('flowchart TD; A --> B');
/// final png = await renderer.renderToPng('flowchart TD; A --> B');
///
/// renderer.dispose();
/// ```
class MermaidRenderer {
  late final JavascriptRuntime _js;
  bool _initialized = false;

  /// Asset path of the mermaid-renderer.js bundle (overridable for testing).
  final String jsAssetPath;

  MermaidRenderer({
    this.jsAssetPath =
        'packages/dmtools_mermaid_renderer/assets/mermaid/mermaid-renderer.js',
  });

  // ─── lifecycle ────────────────────────────────────────────────────────────

  /// Load and evaluate the Mermaid JS bundle.
  ///
  /// Must be called once before [renderToSvg] / [renderToPng].
  /// Safe to call from [WidgetsFlutterBinding.ensureInitialized()] context.
  Future<void> init() async {
    if (_initialized) return;
    _js = getJavascriptRuntime();
    final jsSource = await rootBundle.loadString(jsAssetPath);
    _js.evaluate(jsSource);
    _initialized = true;
  }

  /// Free the JS runtime resources.
  void dispose() {
    if (_initialized) {
      _js.dispose();
      _initialized = false;
    }
  }

  // ─── public API ───────────────────────────────────────────────────────────

  /// Render [definition] to a normalised SVG string.
  ///
  /// The output is suitable for display with [SvgPicture.string] and opens
  /// correctly in Affinity Designer / Inkscape.
  Future<String> renderToSvg(String definition) async {
    _assertInitialized();
    final svg = await _jsRender(definition);
    return SvgNormalizer.normalize(svg);
  }

  /// Render [definition] to PNG bytes.
  ///
  /// The PNG is generated by rendering the normalised SVG through
  /// flutter_svg + dart:ui PictureRecorder (white background, device-pixel
  /// resolution = 1).
  ///
  /// Requires the Flutter widget binding to be initialised:
  /// ```dart
  /// WidgetsFlutterBinding.ensureInitialized();
  /// ```
  Future<Uint8List> renderToPng(String definition) async {
    final svg = await renderToSvg(definition);
    return svgToPng(svg);
  }

  // ─── helpers ──────────────────────────────────────────────────────────────

  void _assertInitialized() {
    if (!_initialized) {
      throw StateError(
          'MermaidRenderer not initialised. Call init() before rendering.');
    }
  }

  Future<String> _jsRender(String definition) async {
    // renderMermaidToSvg(definition, javaMetrics) — pass null for metrics;
    // the JS shim falls back to its built-in estimateTextWidth heuristics.
    final call = 'renderMermaidToSvg(${jsonEncode(definition)}, null)';
    final result = _js.evaluate(call);

    if (result.isError) {
      throw Exception('Mermaid JS error: ${result.stringResult}');
    }

    // Handle the returned Promise (renderMermaidToSvg is async in JS).
    if (result.isPromise) {
      final resolved = await _js.handlePromises(result);
      if (resolved.isError) {
        throw Exception('Mermaid promise rejected: ${resolved.stringResult}');
      }
      return resolved.stringResult;
    }

    return result.stringResult;
  }

  // ─── SVG → PNG conversion (static, reusable) ──────────────────────────────

  /// Convert a normalised SVG string to PNG bytes using flutter_svg + dart:ui.
  ///
  /// The SVG natural [viewBox] / [width] / [height] is used for the output
  /// dimensions.  Supply explicit [width] / [height] to override.
  static Future<Uint8List> svgToPng(
    String svgString, {
    double? width,
    double? height,
  }) async {
    final (w, h) = _parseDimensions(svgString, width, height);

    // flutter_svg 2.x: SvgStringLoader compiles SVG to the vector_graphics
    // binary format; vg.loadPicture turns that into a ui.Picture.
    final loader = SvgStringLoader(svgString);
    final pictureInfo = await vg.loadPicture(loader, null);

    final iw = w.toInt();
    final ih = h.toInt();

    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(
      recorder,
      ui.Rect.fromLTWH(0, 0, w, h),
    );

    // White background (matching Java Batik: KEY_BACKGROUND_COLOR = white).
    canvas.drawRect(
      ui.Rect.fromLTWH(0, 0, w, h),
      ui.Paint()..color = const ui.Color(0xFFFFFFFF),
    );

    // Scale SVG to fit requested dimensions.
    final scaleX = w / pictureInfo.size.width;
    final scaleY = h / pictureInfo.size.height;
    final scale = scaleX < scaleY ? scaleX : scaleY;
    canvas.save();
    canvas.scale(scale);
    canvas.drawPicture(pictureInfo.picture);
    canvas.restore();
    pictureInfo.picture.dispose();

    final picture = recorder.endRecording();
    final image = await picture.toImage(iw, ih);
    picture.dispose();

    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    image.dispose();

    if (byteData == null) {
      throw StateError('dart:ui failed to encode PNG');
    }
    return byteData.buffer.asUint8List();
  }

  /// Parse width/height from SVG viewBox or width/height attributes.
  static (double, double) _parseDimensions(
      String svg, double? overrideW, double? overrideH) {
    double? w = overrideW;
    double? h = overrideH;

    if (w == null || h == null) {
      // Try viewBox first.
      final vbMatch =
          RegExp(r'viewBox="([^"]+)"').firstMatch(svg);
      if (vbMatch != null) {
        final parts = vbMatch.group(1)!.trim().split(RegExp(r'[\s,]+'));
        if (parts.length == 4) {
          w ??= double.tryParse(parts[2]);
          h ??= double.tryParse(parts[3]);
        }
      }
      // Fall back to width/height attributes.
      if (w == null) {
        final wm = RegExp(r'\bwidth="([0-9.]+)"').firstMatch(svg);
        if (wm != null) w = double.tryParse(wm.group(1)!);
      }
      if (h == null) {
        final hm = RegExp(r'\bheight="([0-9.]+)"').firstMatch(svg);
        if (hm != null) h = double.tryParse(hm.group(1)!);
      }
    }

    return (w ?? 800.0, h ?? 600.0);
  }
}
