import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_js/flutter_js.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'svg_normalizer.dart';

/// Dart / Flutter counterpart to the Java {@code MermaidRenderer} class.
///
/// Renders Mermaid diagram DSL to SVG or PNG without a browser:
///
///  * JavaScript engine: flutter_js (QuickJS on Android/Linux, JavaScriptCore
///    on iOS/macOS) — same role as GraalJS in the Java version.
///  * Text metrics: falls back to the built-in JS heuristics inside the bundle
///    (same estimates used when javaMetrics=null in the Java shim).
///  * SVG→PNG: flutter_svg + dart:ui PictureRecorder — replaces Apache Batik.
///
/// Typical usage:
///
/// ```dart
/// final renderer = MermaidRenderer();
/// await renderer.init();
///
/// final svg = await renderer.renderToSvg('flowchart TD; A --> B');
/// final png = await renderer.renderToPng('flowchart TD; A --> B');
///
/// renderer.dispose();
/// ```
class MermaidRenderer {
  late final JavascriptRuntime _js;
  bool _initialized = false;

  /// Asset path of the mermaid-renderer.js bundle (overridable for testing).
  final String jsAssetPath;

  MermaidRenderer({
    this.jsAssetPath =
        'packages/dmtools_mermaid_renderer/assets/mermaid/mermaid-renderer.js',
  });

  // ─── lifecycle ────────────────────────────────────────────────────────────

  /// Load and evaluate the Mermaid JS bundle.
  ///
  /// Must be called once before [renderToSvg] / [renderToPng].
  /// Safe to call from [WidgetsFlutterBinding.ensureInitialized()] context.
  Future<void> init() async {
    if (_initialized) return;
    _js = getJavascriptRuntime();
    final jsSource = await rootBundle.loadString(jsAssetPath);
    _js.evaluate(jsSource);
    _initialized = true;
  }

  /// Free the JS runtime resources.
  void dispose() {
    if (_initialized) {
      _js.dispose();
      _initialized = false;
    }
  }

  // ─── public API ───────────────────────────────────────────────────────────

  /// Render [definition] to a normalised SVG string.
  ///
  /// The output is suitable for display with [SvgPicture.string] and opens
  /// correctly in Affinity Designer / Inkscape.
  Future<String> renderToSvg(String definition) async {
    _assertInitialized();
    final svg = await _jsRender(definition);
    return SvgNormalizer.normalize(svg);
  }

  /// Render [definition] to PNG bytes.
  ///
  /// The PNG is generated by rendering the normalised SVG through
  /// flutter_svg + dart:ui PictureRecorder (white background, device-pixel
  /// resolution = 1).
  ///
  /// Requires the Flutter widget binding to be initialised:
  /// ```dart
  /// WidgetsFlutterBinding.ensureInitialized();
  /// ```
  Future<Uint8List> renderToPng(String definition) async {
    final svg = await renderToSvg(definition);
    return svgToPng(svg);
  }

  // ─── helpers ──────────────────────────────────────────────────────────────

  void _assertInitialized() {
    if (!_initialized) {
      throw StateError(
          'MermaidRenderer not initialised. Call init() before rendering.');
    }
  }

  int _renderCallId = 0;

  Future<String> _jsRender(String definition) async {
    // renderMermaidToSvg returns a JS Promise. flutter_js has no native Promise
    // bridge, so we resolve it via the sendMessage channel:
    //   1. JS .then() fires, calls sendMessage('_dmtools_svg_N', jsonResult)
    //   2. Dart onMessage handler completes the Completer
    //   3. JS .catch() calls sendMessage('_dmtools_err_N', jsonError)
    final id = _renderCallId++;
    final svgCh = '_dmtools_svg_$id';
    final errCh = '_dmtools_err_$id';

    final completer = Completer<String>();

    _js.onMessage(svgCh, (dynamic raw) {
      if (!completer.isCompleted) {
        // raw is the decoded JSON value; if it's already a String, use it.
        final svg = raw is String ? raw : raw.toString();
        completer.complete(svg);
      }
    });

    _js.onMessage(errCh, (dynamic raw) {
      if (!completer.isCompleted) {
        completer.completeError(
            Exception('Mermaid rendering failed: $raw'));
      }
    });

    // Kick off the async render. The .then/.catch callbacks send messages back
    // to Dart which will resolve the completer above.
    _js.evaluate('''
      (function(){
        var _svgCh = ${jsonEncode(svgCh)};
        var _errCh = ${jsonEncode(errCh)};
        renderMermaidToSvg(${jsonEncode(definition)}, null)
          .then(function(svg) { sendMessage(_svgCh, JSON.stringify(svg)); })
          .catch(function(e)  { sendMessage(_errCh,  JSON.stringify('' + e)); });
      })();
    ''');

    return completer.future;
  }

  // ─── SVG → PNG conversion (static, reusable) ──────────────────────────────

  /// Convert a normalised SVG string to PNG bytes using flutter_svg + dart:ui.
  ///
  /// The SVG natural [viewBox] / [width] / [height] is used for the output
  /// dimensions.  Supply explicit [width] / [height] to override.
  ///
  /// On systems where `rsvg-convert` (librsvg) is on PATH it is used for
  /// full-fidelity rendering including fonts and text.  Otherwise falls back
  /// to `flutter_svg` + `dart:ui` which renders shapes and paths correctly but
  /// may not render text labels.
  static Future<Uint8List> svgToPng(
    String svgString, {
    double? width,
    double? height,
  }) async {
    // Try rsvg-convert first — it handles all SVG text/font features that
    // vector_graphics_compiler currently does not support.
    final rsvgPng = await _svgToPngViaRsvg(svgString, width, height);
    if (rsvgPng != null) return rsvgPng;

    // Fallback: flutter_svg + dart:ui (shapes only, text may be missing).
    return _svgToPngViaFlutterSvg(svgString, width, height);
  }

  /// Attempt PNG conversion via the `rsvg-convert` CLI (librsvg).
  /// Returns null if rsvg-convert is not found or fails.
  static Future<Uint8List?> _svgToPngViaRsvg(
      String svgString, double? width, double? height) async {
    try {
      // Write SVG to a temp file.
      final tmpSvg = _tmpFile('svg');
      final tmpPng = _tmpFile('png');
      try {
        File(tmpSvg).writeAsStringSync(svgString, encoding: _utf8);

        final args = <String>[tmpSvg, '-b', 'white', '-o', tmpPng];
        if (width != null) args.addAll(['-w', width.toInt().toString()]);
        if (height != null) args.addAll(['-h', height.toInt().toString()]);

        final result = await Process.run('rsvg-convert', args);
        if (result.exitCode != 0) return null;

        final png = File(tmpPng);
        if (!png.existsSync()) return null;
        return png.readAsBytesSync();
      } finally {
        _tryDelete(tmpSvg);
        _tryDelete(tmpPng);
      }
    } on ProcessException {
      return null; // rsvg-convert not on PATH
    } catch (_) {
      return null;
    }
  }

  static Future<Uint8List> _svgToPngViaFlutterSvg(
    String svgString, double? width, double? height) async {
    final (w, h) = _parseDimensions(svgString, width, height);

    // flutter_svg 2.x: SvgStringLoader compiles SVG to the vector_graphics
    // binary format; vg.loadPicture turns that into a ui.Picture.
    final loader = SvgStringLoader(svgString);
    final pictureInfo = await vg.loadPicture(loader, null);

    final iw = w.toInt();
    final ih = h.toInt();

    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(
      recorder,
      ui.Rect.fromLTWH(0, 0, w, h),
    );

    // White background (matching Java Batik: KEY_BACKGROUND_COLOR = white).
    canvas.drawRect(
      ui.Rect.fromLTWH(0, 0, w, h),
      ui.Paint()..color = const ui.Color(0xFFFFFFFF),
    );

    // Scale SVG to fit requested dimensions.
    final scaleX = w / pictureInfo.size.width;
    final scaleY = h / pictureInfo.size.height;
    final scale = scaleX < scaleY ? scaleX : scaleY;
    canvas.save();
    canvas.scale(scale);
    canvas.drawPicture(pictureInfo.picture);
    canvas.restore();
    pictureInfo.picture.dispose();

    final picture = recorder.endRecording();
    final image = await picture.toImage(iw, ih);
    picture.dispose();

    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    image.dispose();

    if (byteData == null) {
      throw StateError('dart:ui failed to encode PNG');
    }
    return byteData.buffer.asUint8List();
  }

  static final _utf8 = const Utf8Codec();

  static String _tmpFile(String ext) =>
      '${Directory.systemTemp.path}/dmtools_mermaid_${DateTime.now().microsecondsSinceEpoch}.$ext';

  static void _tryDelete(String path) {
    try { File(path).deleteSync(); } catch (_) {}
  }

  /// Parse width/height from SVG viewBox or width/height attributes.
  static (double, double) _parseDimensions(
      String svg, double? overrideW, double? overrideH) {
    double? w = overrideW;
    double? h = overrideH;

    if (w == null || h == null) {
      // Try viewBox first.
      final vbMatch =
          RegExp(r'viewBox="([^"]+)"').firstMatch(svg);
      if (vbMatch != null) {
        final parts = vbMatch.group(1)!.trim().split(RegExp(r'[\s,]+'));
        if (parts.length == 4) {
          w ??= double.tryParse(parts[2]);
          h ??= double.tryParse(parts[3]);
        }
      }
      // Fall back to width/height attributes.
      if (w == null) {
        final wm = RegExp(r'\bwidth="([0-9.]+)"').firstMatch(svg);
        if (wm != null) w = double.tryParse(wm.group(1)!);
      }
      if (h == null) {
        final hm = RegExp(r'\bheight="([0-9.]+)"').firstMatch(svg);
        if (hm != null) h = double.tryParse(hm.group(1)!);
      }
    }

    return (w ?? 800.0, h ?? 600.0);
  }
}
